### ISSUE TITLE
What is the right layout to connect sensor & motors

### ISSUE THREAD

**Issue by jabrena** [DexterInd/BrickPi#28]
Good morning,

I am doing some tests with Brickpi+ for the project:
https://github.com/ev3dev-lang-java/ev3dev-lang-java

and I am not sure what is the best way to connect sensors & motors for brickpi v2.8:

![img](http://rlx.sk/2926-tm_thickbox_default/brickpi-advanced-seeed-kit03800m-raspberry-pi-into-lego-mindstorms-robot.jpg)

In the documentation on the website appear other layout:
http://www.dexterindustries.com/BrickPi/getting-started/attaching-lego/

![img](http://www.dexterindustries.com/wp-content/uploads/2013/07/Sensor_Port_Layout_Yellow-copy.png)

with 5 sensors, but in my board in the position of the 5th sensor, I have the energy connector.
Following other images, I notice that the first row of RJ45 input is for motors and the rest of the connectors is for sensors, isn't it?

Juan Antonio

**Comment by jabrena** [comment]
This layout to connect sensor & motors is right?

![img](https://cdn.sparkfun.com/assets/b/7/2/9/9/Brick_Pi_Hookup_Guide-06.jpg)

**Comment by DexterInd** [comment]
The picture you've got above is for the BrickPi Advanced, the older version (no longer sold).  I'll get an updated picture up there asap.  Thanks for pointing this out!

**Comment by DexterInd** [comment]
This should be updated now.  Thanks or the heads up and reminder!

**Comment by jabrena** [comment]
No problem :)
