### ISSUE TITLE
How to see Brickpi firmware version?

### ISSUE THREAD

**Issue by jabrena** [DexterInd/BrickPi#33]
I would like to know, some way to read the version of BrickPi firmware.

Many thanks in advance.

Juan Antonio

**Comment by dlech** [comment]
https://github.com/DexterInd/BrickPi_Python/blob/a8452123a23e610382f7f18bf4950f2f2a787de6/Sensor_Examples/EV3-Firmware_Check.py

**Comment by DexterInd** [comment]
Indeed, you run the file @dlech recommends and it should help you figure out which version of firmware you're board is running.
