### ISSUE TITLE
time not imported but needed for time.sleep()

### ISSUE THREAD

**Issue by graykevinb** [DexterInd/BrickPi#37]
the time module is not imported but time.sleep() is called.
time.sleep() is called on line 113

**Comment by DexterInd** [comment]
Hey @graykevinb , which file are we referring to here?

**Comment by graykevinb** [comment]
Oh, so sorry. I forgot to say that. Apparently you figured it out from my pull request. Just for the record ita this one: https://github.com/DexterInd/BrickPi/blob/master/Software/BrickPi_Python/Project_Examples/browserBot/RPi_Server_Code.py
