### ISSUE TITLE
Incorrect link on Using BrickPi with "C" 

### ISSUE THREAD

**Issue by maniSbindra** [DexterInd/BrickPi#48]
Hi The link http://www.dexterindustries.com/BrickPi/program-it/c/ redirects to another link which has no information on programming BrickPi with C.

**Comment by CleoQc** [comment]
We do not have a page for the BrickPi3 and C. 
This link would be for the BrickPi+ and C: https://www.dexterindustries.com/BrickPi/brickpi-tutorials-documentation/program-it/c/
